#pragma once
#pragma execution_character_set("utf-8")


#include "Base.h"

#include "wx/wxprec.h"
#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

namespace SparkMap
{
  enum WidgetID
  {
    ID_CIRCLE = wxID_HIGHEST + 1,
    ID_MAIN_FRAME,
    ID_GL_FRAME,
    ID_GL_CANVAS,
    ID_RENDER_TIMER,
    ID_GAUGE,
    ID_CROSS,
    ID_TRIANGLE,
    ID_SQUARE,
    ID_POLYGON,
    ID_SELECTION_EXPAND_H,
    ID_SELECTION_EXPAND_V,
    ID_SELECTION_CONTRACT,
    ID_BUTTON_XX,
    ID_BUTTON_XY,
    ID_PRIMARY_COLOUR,
    ID_SECONDARY_COLOUR,
    ID_DEFAULT_PROVIDER,
    ID_AUI_PROVIDER,
    ID_MSW_PROVIDER,
    ID_MAIN_TOOLBAR,
    ID_POSITION_TOP,
    ID_POSITION_TOP_ICONS,
    ID_POSITION_TOP_BOTH,
    ID_POSITION_LEFT,
    ID_POSITION_LEFT_LABELS,
    ID_POSITION_LEFT_BOTH,
    ID_TOGGLE_PANELS,
    ID_ENABLE,
    ID_DISABLE,
    ID_DISABLED,
    ID_UI_ENABLE_UPDATED,
    ID_CHECK,
    ID_UI_CHECK_UPDATED,
    ID_CHANGE_TEXT1,
    ID_CHANGE_TEXT2,
    ID_UI_CHANGE_TEXT_UPDATED,
    ID_REMOVE_PAGE,
    ID_HIDE_PAGES,
    ID_SHOW_PAGES,
    ID_PLUS_MINUS,
    ID_CHANGE_LABEL,
    ID_SMALL_BUTTON_1,
    ID_SMALL_BUTTON_2,
    ID_SMALL_BUTTON_3,
    ID_SMALL_BUTTON_4,
    ID_SMALL_BUTTON_5,
    ID_SMALL_BUTTON_6,
    ID_MAIN_MENU_ITEM = 16000,
    ID_MAIN_TOOL_ITEM = 17000,
  };
}